### ISSUE TITLE
Meat-producing bees no longer produce proper items

### ISSUE THREAD

**Issue by Teslapirate** [MagicBees/MagicBees#39] opened 2015-04-15 02:04 UTC
magicbees-1.7.10-2.2.1

In this version, poultry, beefy, and porcine bees are no longer producing nuggets; rather, they produce Honey Comb (10%) and Fire (9%). Thaumcraft is installed (4.2.3.5)
![poultrybeefire](https://cloud.githubusercontent.com/assets/1819750/7151010/ca709cc2-e2d8-11e4-99ff-ea059bafdf85.jpg)

**Comment by MysteriousAges** [comment] 2015-04-15 05:21
Duplicate of #36

**Closed by MysteriousAges** 2015-04-15 05:21 UTC
