### ISSUE TITLE
Crash with the 2.2.1 update

### ISSUE THREAD

**Issue by Mistercl0ud** [MagicBees/MagicBees#38] opened 2015-04-14 16:50 UTC
After the 2.2.1 update, the game crashed on world load. I was able to remove 2 bees that were causing the problem : Winsome bees and Endearing bees.

https://gist.github.com/mezz/1cc06fc81a36eb1fdd66

**Comment by MysteriousAges** [comment] 2015-04-14 20:31
Most likely related to #36.

**Comment by Mistercl0ud** [comment] 2015-04-14 23:55
Well I don't have gendustry. I do have binnie's mod extra bees. And the problem only started after the update to 2.2.1.

**Comment by MysteriousAges** [comment] 2015-04-15 00:29
The root cause produces both issues - bee species are initialized before all the mod helpers have had a chance to get the product items.

**Comment by MysteriousAges** [comment] 2015-04-15 05:21
Duplicate of #36

**Closed by MysteriousAges** 2015-04-15 05:21 UTC
