### ISSUE TITLE
MagicBees + OpenPeripheral: Java NullPointException when calling getBeeBreedingData

### ISSUE THREAD

**Issue by YYCMichael** [MagicBees/MagicBees#100] opened 2015-09-23 18:30 UTC
Hi,

Calling apiary.getBeeBreedingData gives the following results:
java.lang.NullPointerException without any info

Running FTB Infinity 1.10.1 with:
forestry_1.7.10-3.6.3.20
OpenModsLib-1.7.10-0.8
OpenPeripheralAddons-1.7.10-0.4
OpenPeripheralCore-1.7.10-1.2
OpenPeripheralIntegration-1.7.10-0.3

A bug was opened here https://github.com/OpenMods/OpenPeripheral-Integration/issues/19

From the issue thread with OpenPeripheral, the following was observed:

```
With some debugging I found out that faulty species is: BM_BOUND (Blood Magic?) and problem is caused by BeeMutation.requiredBlock == null.

Only thing I can do is add sanity check and ignore faulty bee. Please report this issue to MagicBees
```

Log is below (thank you to Boq):

```
[17:55:22] [Coroutine-2/DEBUG] [OpenMods/]: Error during method getBeeBreedingData(6) execution on peripheral apiculture_2_name, args: []
java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
    at magicbees.bees.BeeMutation.getSpecialConditions(BeeMutation.java:538) ~[BeeMutation.class:?]
    at openperipheral.integration.forestry.AdapterBeeHousing.getBeeBreedingData(AdapterBeeHousing.java:78) ~[AdapterBeeHousing.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
    at openperipheral.adapter.method.MethodDeclaration$CallWrap.call(MethodDeclaration.java:308) ~[MethodDeclaration$CallWrap.class:?]
    at openperipheral.adapter.method.MethodDeclaration$CallWrap.call(MethodDeclaration.java:322) ~[MethodDeclaration$CallWrap.class:?]
    at openperipheral.interfaces.cc.wrappers.AdapterPeripheral.call(AdapterPeripheral.java:64) [AdapterPeripheral.class:?]
    at openperipheral.interfaces.cc.wrappers.AdapterPeripheral.callMethod(AdapterPeripheral.java:85) [AdapterPeripheral.class:?]
    at dan200.computercraft.core.apis.PeripheralAPI$PeripheralWrapper.call(PeripheralAPI.java:110) [PeripheralAPI$PeripheralWrapper.class:?]
    at dan200.computercraft.core.apis.PeripheralAPI.callMethod(PeripheralAPI.java:477) [PeripheralAPI.class:?]
    at dan200.computercraft.core.lua.LuaJLuaMachine$2.invoke(LuaJLuaMachine.java:332) [LuaJLuaMachine$2.class:?]
    at org.luaj.vm2.lib.VarArgFunction.onInvoke(Unknown Source) [VarArgFunction.class:?]
    at org.luaj.vm2.TailcallVarargs.eval(Unknown Source) [TailcallVarargs.class:?]
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.execute(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.lib.BaseLib.pcall(Unknown Source) [BaseLib.class:?]
    at org.luaj.vm2.lib.BaseLib$BaseLibV.invoke(Unknown Source) [BaseLib$BaseLibV.class:?]
    at org.luaj.vm2.LuaClosure.execute(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.execute(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.lib.BaseLib.pcall(Unknown Source) [BaseLib.class:?]
    at org.luaj.vm2.lib.BaseLib$BaseLibV.invoke(Unknown Source) [BaseLib$BaseLibV.class:?]
    at org.luaj.vm2.LuaClosure.execute(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.execute(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.TailcallVarargs.eval(Unknown Source) [TailcallVarargs.class:?]
    at org.luaj.vm2.TailcallVarargs.arg1(Unknown Source) [TailcallVarargs.class:?]
    at org.luaj.vm2.LuaClosure.call(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.execute(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.execute(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.lib.BaseLib.pcall(Unknown Source) [BaseLib.class:?]
    at org.luaj.vm2.lib.BaseLib$BaseLibV.invoke(Unknown Source) [BaseLib$BaseLibV.class:?]
    at org.luaj.vm2.LuaClosure.execute(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.call(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.execute(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source) [LuaClosure.class:?]
    at org.luaj.vm2.LuaThread$State.run(Unknown Source) [LuaThread$State.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_31] 
```

**Comment by YYCMichael** [comment] 2015-09-24 16:13
Temp fix was downgrade to magicbees-1.7.10-2.3.1

**Comment by MysteriousAges** [comment] 2015-09-27 23:48
And what version of Blood magic is this happening with?

**Comment by YYCMichael** [comment] 2015-09-28 01:09
BloodMagic-1.7.10-1.3.3-11

**Comment by MysteriousAges** [comment] 2015-09-30 00:11
Looks like a dupe of #90. Please use a more recent version of MB.

**Closed by MysteriousAges** 2015-09-30 00:11 UTC

**Comment by YYCMichael** [comment] 2015-09-30 01:51
I don't see how this is a duplicate when issue #90 crashes the client entirely whereas #100 only occurs when using ComputerCraft to call data. Also, I was using the most recent version of Magic Bees but a downgrade to 2.3.1 self-resolved the issue. In other words whatever changed between 2.3.1 and 2.3.3 makes this problem re-occur.

I'll give 2.3.6 a try.

**Comment by MysteriousAges** [comment] 2015-09-30 20:06
Different code paths invoking the same function and getting a null. One catches the exception and doesn't crash, the other is uncaught and crashes the client.

**Comment by YYCMichael** [comment] 2015-09-30 20:12
Ah. Thanks for that explanation. :)
