### ISSUE TITLE
Hiveacynth crashes the server

### ISSUE THREAD

**Issue by radebrecht** [MagicBees/MagicBees#49] opened 2015-04-25 15:04 UTC
Hiveacynth crashes the server. Maybe related to #47?

```
[25/4/2015 16:51:18 PM] [Server thread/ERROR]: Encountered an unexpected exception
[25/4/2015 16:51:18 PM] net.minecraft.util.ReportedException: Ticking block entity
[25/4/2015 16:51:18 PM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
[25/4/2015 16:51:18 PM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
[25/4/2015 16:51:18 PM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
[25/4/2015 16:51:18 PM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[25/4/2015 16:51:18 PM] 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[25/4/2015 16:51:18 PM] Caused by: java.lang.NullPointerException
[25/4/2015 16:51:18 PM] 	at magicbees.main.utils.compat.botania.SubTileHiveacynth.getRandomBee(SubTileHiveacynth.java:56) ~[SubTileHiveacynth.class:?]
[25/4/2015 16:51:18 PM] 	at magicbees.main.utils.compat.botania.SubTileHiveacynth.onUpdate(SubTileHiveacynth.java:42) ~[SubTileHiveacynth.class:?]
[25/4/2015 16:51:18 PM] 	at vazkii.botania.common.block.tile.TileSpecialFlower.func_145845_h(TileSpecialFlower.java:92) ~[TileSpecialFlower.class:?]
[25/4/2015 16:51:18 PM] 	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
[25/4/2015 16:51:18 PM] 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
[25/4/2015 16:51:18 PM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
[25/4/2015 16:51:18 PM] 	... 4 more

```

Mods:
```
1.7.10-Pistronics2-v0.5.8.jar                
AOBD-2.5.0.jar                               
Baubles-1.7.10-1.0.1.10.jar                  
BiblioCraft[v1.10.3][MC1.7.10].jar           
BiblioWoods[Forestry][v1.7].jar              
Botania r1.6-183.jar                         
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
DragonAPI 1.7.10 V6f.jar                     
ElectriCraft 1.7.10 V6a.jar                  
ExpandedRedstone 1.7.10 V6a.jar              
GeoStrata 1.7.10 V6a.jar                     
GraveStone-2.12.2.jar                        
InventoryTweaks-1.59-dev-152.jar             
Mantle-1.7.10-0.3.2.jar                      
MineTweaker3-1.7.10-3.0.9C.jar               
MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar   
NEIIntegration-MC1.7.10-1.0.9.jar            
NotEnoughItems-1.7.10-1.0.4.83-universal.jar 
RPGAdvMod-1.0.0_1.7.10.jar                   
Railcraft_1.7.10-9.5.0.0.jar                 
ReactorCraft 1.7.10 V6e.jar                  
RedstonePasteMod-1.7.10-1.6.2.jar            
RotaryCraft 1.7.10 V6f.jar                   
TConstruct-1.7.10-1.8.3b.jar                 
TiCTooltips-mc1.7.10-1.2.3.jar               
binnie-mods-2.0-pre8.jar                     
denseores-1.5.jar                            
fastcraft-1.21.jar                           
forestry_1.7.10-3.5.4.13.jar                 
hopperductmod-1.7.10-1.3.2.jar               
magicbees-1.7.10-2.2.3.jar                   
neiaddons-mc1710-1.12.5.17.jar               
```

**Comment by MysteriousAges** [comment] 2015-04-25 16:43
Duplicate of #42 - I derped on the Extra Bees species names. Turn off the Hiveacynth, or upgrade to 2.3.0-beta.

**Closed by MysteriousAges** 2015-04-25 16:43 UTC
