### ISSUE TITLE
Botania recipes broken

### ISSUE THREAD

**Issue by Bennyboy1695** [MagicBees/MagicBees#126] opened 2016-02-07 04:44 UTC
On infinity version 2.3.5 any recipes added by magic bees that contain mana petals in the recipes have broken an in replace of the mana petals is minecraft fire.

http://goo.gl/OPp9Ey
http://goo.gl/8iHzbH
http://goo.gl/Xtq8nD

**Comment by Bennyboy1695** [comment] 2016-02-07 05:26
Just found out thats its caused by mana petals being removed from botania bild 1.8-238 which has caused the issue

**Comment by mezz** [comment] 2016-02-07 21:39
Thanks for the report!
This is fixed in the latest version of Magic Bees.
Duplicate of #116

**Closed by mezz** 2016-02-07 21:39 UTC
