### ISSUE TITLE
Game Crash When i Add Magic Bees to Mod pack 

### ISSUE THREAD

**Issue by Devtech223** [MagicBees/MagicBees#125] opened 2016-01-28 20:58 UTC
http://pastebin.com/3aNNEF7e
games crashes when i add magic bees in

**Comment by Devtech223** [comment] 2016-01-29 04:14
Magic Bees work in my pack if i use 2.4.0 
2.4.2 does not work

**Comment by mezz** [comment] 2016-01-29 04:20
Thanks for the report!
This is a duplicate of #124

**Closed by mezz** 2016-01-29 04:20 UTC
