### ISSUE TITLE
Crash on startup, not sure why.

### ISSUE THREAD

**Issue by Plurp13** [MagicBees/MagicBees#89] opened 2015-08-04 18:16 UTC
I really wanna play with this mod but have been unable to because it keeps crashing before the game's even done loading. I've tried it with that old link from when it said it wasn't being maintained and the new version from this month. I'll try going back a version if I can find the previous version to go back to but for now here's the crash report.

http://pastebin.com/RGykN9xR

I'm not actually sure if it's magic bees or thaumcraft that's crashing, because it mentions thaumcraft up there at the beginning, all I know is it doesn't crash unless I add magic bees. I'll go report it on the thaumcraft page too just in case.

I can confirm it's an issue with thaumcraft, I loaded up just thaumcraft, magic bees, and forestry and still got the crash, then I took out thaumcraft and it loaded up fine. Here's the crash report with just the three mods plus forge. http://pastebin.com/H0pP2vPs

**Comment by Plurp13** [comment] 2015-08-07 05:01
I have, under recommendation from someone in the thaumcraft forum, switched from the latest forge to the recommended forge, and I still get the exact same crash. )=

**Comment by MysteriousAges** [comment] 2015-08-19 23:15
It's an integration issue, nothing to do with Forge/Thaumcraft. I'll take a look.

**Comment by Plurp13** [comment] 2015-08-20 00:55
Thank you!

**Comment by MysteriousAges** [comment] 2015-08-25 22:33
Have you switched off any Forestry modules in the config? I can't reproduce this crash with default configs.

**Comment by Plurp13** [comment] 2015-09-17 02:35
Oh wow this was forever ago sorry. Yeah I turned off everything but bees I really only wanted bees, I suppose I should reset the config and see if it works huh?

**Comment by mezz** [comment] 2015-09-17 05:46
Just an FYI, I added a line to the end of crashlogs that says what Forestry modules are disabled
>Forestry : Info: The following plugins have been disabled in the config: arboriculture, lepidopterology, mail

**Comment by Plurp13** [comment] 2015-09-18 15:56
Ok so I tried again with the newest forestry and magic bees and a fresh config file so all the modules are active and it still crashes. Here's the crash log.
http://pastebin.com/jDbgbeMa

**Comment by MysteriousAges** [comment] 2015-09-18 22:30
Bump your Forestry version to 3.6+ to use the recent builds. You'll also get some extra bug fixes in Forestry if you doooo~

**Comment by Plurp13** [comment] 2015-09-18 22:46
Yeah I realized it wasn't actually the newest. Have it now, about to add in magic bees and see if it works now.

**Comment by Plurp13** [comment] 2015-09-18 22:56
Ok, this is interesting. I moved all my configs elsewhere so it would have to recreate all of them for the three mods I'm trying to get to work here, and now it's opened, but it's doing this funny thing with the words.
![screen shot 2015-09-18 at 6 54 23 pm](https://cloud.githubusercontent.com/assets/8428847/9972797/d98f26c2-5e36-11e5-9bc5-316c7487c07d.png)

Ah well, at least it works now. I still have no idea what was wrong with it in the first place though...

**Comment by Plurp13** [comment] 2015-09-18 23:41
Aha, I have come to a conclusion, magic bees doesn't like it if I turn off the arboriculture module, as long as I leave that on It's all good. ^.^

**Comment by MysteriousAges** [comment] 2015-09-22 22:12
Yeah, it doesn't yet support disabling Forestry modules. It's on the to-do list as #93. Will close this one; track it there, and such. :U

**Closed by MysteriousAges** 2015-09-22 22:12 UTC
